/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/projects/": {
    get: operations["api_projects_list"];
    post: operations["api_projects_create"];
  };
  "/api/projects/{id}/": {
    get: operations["api_projects_retrieve"];
    put: operations["api_projects_update"];
    delete: operations["api_projects_destroy"];
    patch: operations["api_projects_partial_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PatchedProject: {
      project_name?: string;
      year?: number;
      client?: string;
    };
    Project: {
      project_name: string;
      year: number;
      client: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  api_projects_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  api_projects_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
        "application/x-www-form-urlencoded": components["schemas"]["Project"];
        "multipart/form-data": components["schemas"]["Project"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  api_projects_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this dfsm project. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  api_projects_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this dfsm project. */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
        "application/x-www-form-urlencoded": components["schemas"]["Project"];
        "multipart/form-data": components["schemas"]["Project"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  api_projects_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this dfsm project. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_projects_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this dfsm project. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProject"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
        "multipart/form-data": components["schemas"]["PatchedProject"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
}
