import {createApi, fetchBaseQuery} from "@reduxjs/toolkit/query/react";

/**
 * This is an empty API slice that will be injected endpoints autogenerated using an OpenAPI definition.
 * The OpenAPI definition is fetched from casita's backend server.
 */

export const emptySplitApi = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: "http://localhost:8000/api",
    prepareHeaders: async (headers) => {
      const res = await fetch(
        "http://localhost:3000/api/auth/accessTokens"
      ).then((res) => res.json());
      if (res.accessToken) {
        headers.set("authentication", `Bearer ${res.accessToken}`);
      }

      console.log(headers);
      return headers;
    },
  }),
  endpoints: () => ({}),
});
