import {createApi, fetchBaseQuery} from "@reduxjs/toolkit/query/react";
import {RootState} from "@/store/index";

/**
 * This is an empty API slice that will be injected endpoints autogenerated using an OpenAPI definition.
 * The OpenAPI definition is fetched from casita's backend server.
 */
export const emptySplitApi = createApi({
  baseQuery: fetchBaseQuery({
    baseUrl: "http://localhost:8000/api",
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).auth.credentials?.accessToken;
      console.log(`Setting headers to ${token}`);
      if (token) {
        headers.set("authentication", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: () => ({}),
});
