import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>
          <div className="bg-gradient-to-br from-slate-950 to-violet-950 h-screen w-screen">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
