"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import AccessTokenProvider from "@/components/AccessTokenProvider";
import { Provider } from "react-redux";
import { store } from "@/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <Provider store={store}>
          <AccessTokenProvider />
          <body className={`${inter.className} `}>
            <div className="bg-gradient-to-br from-slate-950 to-violet-950 h-screen w-screen">
              {children}
            </div>
          </body>
        </Provider>
      </UserProvider>
    </html>
  );
}
